name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  ACTION_NAME: run-runbook-action
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: '*'
      - run: npm run all
  release-please:
    name: Release
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          package-name: ${{env.ACTION_NAME}}
          release-type: node